---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: debian-9.0

suites:
  - name: default
    data_bags_path: 'test/integration/data_bags'
    encrypted_data_bag_secret_key_path: 'test/integration/encrypted_data_bag_secret'
    run_list:
      - recipe[home_server::default]
    attributes:
      aw_samba:
        network: 10.0.2.0/24
      backuppc:
        cgi:
          admin_pass: admin
          certificate: '/etc/ssl/certs/ssl-cert-snakeoil.pem'
          certificate_key: '/etc/ssl/private/ssl-cert-snakeoil.key'
      openssh:
        server:
          allow_users: 'vagrant'
          password_authentication: 'yes'
          challenge_response_authentication: 'yes'
